### ISSUE TITLE
[FEATURE] Chat Bubbles

### ISSUE THREAD

**Issue by KaspianDev** [Tanguygab/TAB-Additions#10]
Since TAB also manages Nametags, what about chat bubbles in this addon?

**Comment by Tanguygab** [comment]
could be possible 🤔

**Comment by KaspianDev** [comment]
Maybe with some juicy features like per rank format for bubbles etc

**Comment by Tanguygab** [comment]
well I could simply link it to my chat feature so it takes the chat format of the player, which means it would also support the custom channels/conditions/view-conditions thingies and all that stuff that breaks my head x)

**Comment by Tanguygab** [comment]
oops, didn't mean to do that

**Comment by KaspianDev** [comment]
btw the site where you host jars is kinda down

**Comment by Tanguygab** [comment]
Yeah I know, atm I'm only sending them to people who ask me on Discord, I'll probably just use GitHub for now

**Comment by Tanguygab** [comment]
I've kind of did it, I've just added a %rel_chat% placeholder which you can use in one of your nametag lines, and which will update itself each time you chat, and remove itself after a specific amount of time (3000ms by default, can be changed in chat.yml)

Though the unloading is kinda bugged, so I didn't release it yet

**Comment by Tanguygab** [comment]
welp, nvm, it's here https://github.com/Tanguygab/TAB-Additions/releases/tag/1.6.3
