### ISSUE TITLE
Invalid skin definition: ""

### ISSUE THREAD

**Issue by zoyer2** [Tanguygab/TAB-Additions#11]
When enabling real-fake-players im getting spammed by that message.

Where do i get the skin definition from? What am i suppose to put there.

I know it's a features that have bugs, is it one of them? Also not sure but adding fake players to a group works but it sadly doesnt get any prefix from the group :/

Great addon, loving it but i just need those solve this x)

**Comment by Tanguygab** [comment]
haven't checked that feature in a while, and I'm not really interested in keeping it
I can try to take a look though, the prefix issue is probably because TAB uses the groups.yml file now and I forgot to update, idk about skins though, it should work the same way as TAB's layout's skins

**Comment by Tanguygab** [comment]
actually it's just me being stupid and writing prefix and suffix instead of tabprefix and tabsuffix x) I'll fix that

**Comment by zoyer2** [comment]
Ah i see, that would be nice to be able to use since the name value has a pretty low amount of character restriction when wanting to add colour etc :D 0

**Comment by Tanguygab** [comment]
well you can still use prefix and suffix for that one rfp, just the ones taken from the group aren't correct 😅

**Comment by zoyer2** [comment]
Skin worked perfectly like  you said, when using tabs format, sry bout that. using prefix and suffix not taken from the group, how is that format?

I'm doing this rn:
![image](https://user-images.githubusercontent.com/60471530/162572596-d3c92e46-a1f0-4854-af74-03bf32bc476e.png)

and after reloading tab it doesnt show up :S

**Comment by Tanguygab** [comment]
in here it should be `prefix` 👀 eh, anyways, I'll try to find out and fix it

**Comment by Tanguygab** [comment]
I've updated that jar in https://github.com/Tanguygab/TAB-Additions/releases/tag/1.6.3
let me know if it works (both groups' tabprefix/tabsuffix & rfp's prefix/suffix should work)

**Comment by zoyer2** [comment]
Works great! The prefix/suffix worked at the beginning but couldnt get it to work now, probably made some mistake. Im using groups now anyway and it works perfect with prefixes etc :)

Thanks a bunch, you're the man!
