### ISSUE TITLE
Bug with /msg on Bungeecord.

### ISSUE THREAD

**Issue by Kydaix** [Tanguygab/TAB-Additions#13]
**Spigot:** 1.8.8
**Bungeecord:** Aegis Escanor 1.7.3
**TAB:** 3.1.1
**TAB-Additions:** 1.6.3
**TAB-Bridge:** 2.0.2

TAB and TAB-Additions are both installed on the Bungeecord. TAB-Bridge on the spigot server.

**Problem:** When I do `/msg PLAYER`,  it kicks me saying `End of stream` and generates logs.

**Logs:** https://pastebin.com/a6jf27ez

**Comment by Tanguygab** [comment]
whoops, my bad! Updated the release https://github.com/Tanguygab/TAB-Additions/releases/tag/1.6.3

**Comment by Kydaix** [comment]
Thanks for being fast, I will try this tomorrow!

**Comment by Kydaix** [comment]
Hey!
I found another bug!

**Here it is:** When I do `/msg` without mentionning anything, it returns a red message `No online player found with the name ""`

**To reproduce:** Simply do `/msg`.
![Capture](https://user-images.githubusercontent.com/90114872/173191233-68f69fc3-fefd-4403-9091-5cd01391f757.PNG)

**Comment by Tanguygab** [comment]
I think I was just too lazy to add that x) I'll add it

**Comment by Tanguygab** [comment]
added https://github.com/Tanguygab/TAB-Additions/releases/tag/1.6.3

**Comment by Kydaix** [comment]
Oh x) No problem! Thank you!
