### ISSUE TITLE
Impossible to load the plugin.

### ISSUE THREAD

**Issue by Kydaix** [Tanguygab/TAB-Additions#14]
**Spigot:** 1.8.8
**Bungeecord:** [XCord 1.36D-BETA](https://www.mc-market.org/resources/16843/updates)
**TAB:** 3.1.2
**TAB-Additions:** 1.6.3
**TAB-Bridge:** 2.0.2

TAB and TAB-Additions are both installed on the Bungeecord. TAB-Bridge on the spigot server.

**Problem:** When I start my Bungeecord server, when TAB-Additions loads, it generates errors then does not work.
Maybe it's because the plugin is not up to date with 1.19?

**Logs:** https://pastebin.com/mL0xnbhV

**Comment by Tanguygab** [comment]
oh right... forgot to fix that I guess, nah it's not related to 1.19, just some changes that TAB did that I forgot to update in my code

**Comment by Tanguygab** [comment]
updated https://github.com/Tanguygab/TAB-Additions/releases/tag/1.6.3

**Comment by Kydaix** [comment]
The fix works! Thanks a lot!
