### ISSUE TITLE
Send messages to plugins in backend servers.

### ISSUE THREAD

**Issue by Kydaix** [Tanguygab/TAB-Additions#15]
**Spigot:** 1.8.8
**Bungeecord:** [XCord 1.36D-BETA](https://www.mc-market.org/resources/16843/updates)
**TAB:** 3.1.2
**TAB-Additions:** 1.6.3
**TAB-Bridge:** 2.0.3

TAB and TAB-Additions are both installed on the Bungeecord. TAB-Bridge on the spigot server.

**Problem:** Here is what I found!
When TAB-Additions is installed on the Bungeecord server, I activate the chat module.
However, I have plugins on my Spigot servers that can request information that they get through the chat (The player writes in the chat and the plugin gets the input).
However, if TAB-Additions is installed on the Bungeecord, and its chat module is enabled, then it is impossible for the plugin on the backend server (Spigot) to retrieve the input.

_Note:_ Of course I can enable `chat-from-bukkit-bridge` but then there is no formating anymore, so I don't see the goal.

**No logs.**

**Comment by Tanguygab** [comment]
I had a modified version of the TAB-Bridge to make this work, but I don't remember if I updated it or not, I'll have to check, but rn it's almost 2am for me so I'll check after sleeping 😅

**Comment by Kydaix** [comment]
Yep no problem, I live in France too. 😄

**Comment by Tanguygab** [comment]
Updated
https://github.com/Tanguygab/TAB-Additions/releases/download/1.6.3/TAB-Bridge-2.0.3.jar

**Comment by Kydaix** [comment]
Ok, thanks, will this be implemented in the TAB-Bridge on MC-Market?

**Comment by Kydaix** [comment]
Il faut bien activer l'option `chat` du plugin TAB-Bridge et ensuite l'option `chat-from-bukkit-bridge` de TAB-Additions ? Ou seulement `chat` de TAB-Bridge ?

Car dans les deux cas ça ne fonctionne pas pour ma part, si j'active `chat-from-bukkit-bridge`, ok ça fonctionne mais je n'ai plus aucun formatage, ni commande, de TAB-Additions.

**Comment by Tanguygab** [comment]
les 2

**Comment by Tanguygab** [comment]
ALORS.... je viens de check le code, et jsp comment j'ai fait, mais j'ai inversé le truc x) faut désactiver `chat` dans la config du TAB-Bridge pour que ça marche ptdrr

**Comment by Tanguygab** [comment]
https://github.com/Tanguygab/TAB-Additions/releases/download/1.6.3/TAB-Bridge-2.0.3.jar
on espère que c'est bon cette fois

**Comment by Kydaix** [comment]
Ahahahah x) Vas-y pas de problème ! Merci pour l'aide, je teste ça et je te dis.
