### ISSUE TITLE
[BUG] About the "nametag-in-range:" feature [MC Version 1.12.2]

### ISSUE THREAD

**Issue by TeQTabanca** [Tanguygab/TAB-Additions#17]
**I changed the `"nametag-in-range:"` property for the first time and after the /tab reload command, if the player is on the server and waiting anywhere, that player's nametag will be fixed in that place. The only solution would be to restart the server.**

![image](https://user-images.githubusercontent.com/89253304/184435957-91f67029-4d1a-4551-aa82-c104966f18f2.png)

**Comment by TeQTabanca** [comment]
**I'm correcting. I set it to `"nametag-in-range: 2"` and restarted the server. If you use the `"/tab reload"` command without touching the settings and then the player is on the server and the player is waiting anywhere, the player's name tag will remain there.**

**Comment by Tanguygab** [comment]
I was able to reproduce it, I'll see what I can do

**Comment by TeQTabanca** [comment]
**Additionally, I set `"tablist-names-radius: 2"` and used the /tab reload command and the player disappeared, but after setting it to `0`, the player still does not appear and does not appear even if I go next to it.**

**Comment by TeQTabanca** [comment]
**There is one more problem. Scoreboard not working properly after updating your plugin.**

### Player with authorized scoreboard authority
```.yml
    yetkili_panosu:
      display-condition: permission:tab.scoreboard.admin
      title: '&b&lYETKİLİ &a&lPANOSU'
      lines:
      - '&e&lOyuncu &a&lBilgileri&f&l:'
      - '&f&lToplam &e&lOyuncu &f&lSayısı: '
      - '&a&l%online%&f&l/&e&l%server_max_players%'
      - '&f&lMevcut &b&lDünyada &a&lBulunan &e&lOyuncu &f&lSayısı:'
      - '&a&l%worldonline%'
      - ' '
      - '&f&lToplam &a&lParan&f&l:'
      - '&a&l%xconomy_balance%'
      - ' '
      - '&b&lSunucu &a&lBilgileri&f&l:'
      - '&f&lTPS: %server_tps_1_colored%'
      - '&a&lÇalışma &f&lSüresi&7:'
      - '&a&l%server_uptime%'
      - '&b&lHafıza &a&lKullanımı&f&l:'
      - '&a&l%memory-used%&f&l/&e&l%memory-max%'
```
![image](https://user-images.githubusercontent.com/89253304/184508716-0b609301-a481-454c-85eb-847485a4cbed.png)

### Unauthorized player's scoreboard

```.yml
    oyuncu_panosu:
      title: '&b&lOYUNCU &a&lPANOSU'
      lines:
      - '%animation:TeqTabanca_Sunucusu%'
      - ' '
      - '&b&lİstatistiklerin&f&l:'
      - '&f&lToplam &a&lÖldürmen&f&l:'
      - '&a&l%pvplevels_kills%'
      - '&f&lToplam &c&lÖlmen&f&l:'
      - '&c&l%pvplevels_deaths%'
      - '&f&lToplam &a&lParan&f&l:'
      - '&a&l%xconomy_balance%'
      - '&5&lLigin&f&l: %alonsoleagues_league_tag%'
      - '&e&lSeviyen&f&l: &e&l%alonsolevels_level%'
      - '&f&lPingin: %player_colored_ping%&f&lms'
      - '&a&lBulunduğun &b&lDünya&f&l:'
      - '&b&l%world%'
```

![image](https://user-images.githubusercontent.com/89253304/184508888-bd44f7dc-9ff5-4ef3-9387-83a82c54264c.png)


### In addition, the player's scoreboard is corrupted after the authorized scoreboard gives permission to the player who does not have permission and takes it back.

![image](https://user-images.githubusercontent.com/89253304/184508983-88a7c1c8-4679-4771-96bc-4d6497750cbd.png)

**Comment by Tanguygab** [comment]
welp, this was an easier fix that I thought... I'll post an update in a few minutes.
About the scoreboard, I didn't really understand what the problem was, but TAB-Additions doesn't interfere with it at all 🤷

**Comment by Tanguygab** [comment]
https://github.com/Tanguygab/TAB-Additions/releases/tag/1.6.5

**Comment by TeQTabanca** [comment]
> welp, this was an easier fix that I thought... I'll post an update in a few minutes. About the scoreboard, I didn't really understand what the problem was, but TAB-Additions doesn't interfere with it at all 🤷

**It's not related to the TAB-Additions plugin anyway. It's about the TAB plugin! I wanted to say that there is a problem with the scoreboards that ask for permission. If you look carefully at the Authority scoreboard, some placeholders are not visible and when you delete the "`tab.scoreboard.admin`" permission from the player, articles that are not in the default scoreboard appear. Articles that are not actually found are in the Authorized scoreboard.**

**Comment by TeQTabanca** [comment]
**In addition, the problem still persists.**

![image](https://user-images.githubusercontent.com/89253304/184862020-75457901-8fcb-40a0-b513-ec88d379d25d.png)

**Comment by TeQTabanca** [comment]
**"`The "tablist-names-radius:`" issue still persists and the player's name tag is showing.**

![image](https://user-images.githubusercontent.com/89253304/184864241-a95a6350-dd10-4a4c-9e3e-94befe72dc39.png)

**Comment by Tanguygab** [comment]
👀

**Comment by Tanguygab** [comment]
doesn't happen to me anymore o_O are you sure you downloaded 1.6.5 ?

**Comment by Tanguygab** [comment]
> **"The "tablist-names-radius:" issue still persists and if the nametag-in-range: property is set, the player will be hidden but the nametag will be visible.**
> 
> ![image](https://user-images.githubusercontent.com/89253304/184864241-a95a6350-dd10-4a4c-9e3e-94befe72dc39.png)

set the same number for both tablist-names-radius and nametag-in-range

**Comment by TeQTabanca** [comment]
> > **"The "tablist-names-radius:" issue still persists and if the nametag-in-range: property is set, the player will be hidden but the nametag will be visible.**
> > ![image](https://user-images.githubusercontent.com/89253304/184864241-a95a6350-dd10-4a4c-9e3e-94befe72dc39.png)
> 
> set the same number for both tablist-names-radius and nametag-in-range

**I already set it like that**

**Comment by Tanguygab** [comment]
I'm not sure, did you restart your server after updating TAB-Additions 1.6.5 ?

**Comment by TeQTabanca** [comment]
> I'm not sure what's wrong, did you restart your server after updating TAB-Additions 1.6.5 ?

**I shut down the server and deleted `Tab-Additions` version `1.6.4` and all the `files` in it and installed version `1.6.5`**

**Comment by Tanguygab** [comment]
can you send your TAB-Additions config ? and what's your plugin list?

**Comment by TeQTabanca** [comment]
> can you send your TAB-Additions config ? and what's your plugin list?

There are more than 70-80 plugins but there is no conflicting plugin with your plugin.

[config.yml](https://github.com/Tanguygab/TAB-Additions/files/9351117/config.zip)

**Comment by TeQTabanca** [comment]
**The `admin scoreboard` was working fine in `TAB-v3.1.1` version, but the `admin scoreboard` is not working properly in the `current version`.**

### Default Admin ScoreBoard:

![image](https://user-images.githubusercontent.com/89253304/184891216-a7809b83-dfad-46e3-8277-294114b6fd0b.png)


Adjusted Admin ScoreBoard:

![image](https://user-images.githubusercontent.com/89253304/184891546-c5a06491-b0cb-44f7-bd23-657bddff3ca7.png)

**Comment by Tanguygab** [comment]
> > can you send your TAB-Additions config ? and what's your plugin list?
> 
> There are more than 70-80 plugins but there is no conflicting plugin with your plugin.
> 
> [config.yml](https://github.com/Tanguygab/TAB-Additions/files/9351117/config.zip)

I don't see anything wrong, can you try on a server with only TAB and TAB-Additions?


> **The `admin scoreboard` was working fine in `TAB-v3.1.1` version, but the `admin scoreboard` is not working properly in the `current version`.**
> 
> ### Default Admin ScoreBoard:
> ![image](https://user-images.githubusercontent.com/89253304/184891216-a7809b83-dfad-46e3-8277-294114b6fd0b.png)
> 
> Adjusted Admin ScoreBoard:
> 
> ![image](https://user-images.githubusercontent.com/89253304/184891546-c5a06491-b0cb-44f7-bd23-657bddff3ca7.png)

join TAB's Discord server for support
