### ISSUE TITLE
Chat shows up for DiscordSRV when in Staff Chat mode

### ISSUE THREAD

**Issue by Catches** [Tanguygab/TAB-Additions#19]
![image](https://user-images.githubusercontent.com/105005455/191650490-ce177885-b8c8-43b3-89cf-15d97eca096c.png)
![image](https://user-images.githubusercontent.com/105005455/191650505-1700b0dc-aba7-437c-8785-b92558c9eeeb.png)

Also for the [item], it's fixed, but for some reason it doesn't work with custom enchantments, while it worked awhile before, for example, items like this
![image](https://user-images.githubusercontent.com/105005455/191650751-0e1a1763-174a-49d0-bad3-aedd950db764.png)
show up as this in [item]
![image](https://user-images.githubusercontent.com/105005455/191650773-091ad233-ce8b-481d-9626-81de46509b54.png)

**Comment by Tanguygab** [comment]
send your chat.yml file

**Comment by Tanguygab** [comment]
Your staffchat format doesn't have anyview condition. 
add `view-condition: "permission:tab.staff"` to your staffchat format

**Comment by Tanguygab** [comment]
yes, like that, what does it do now?

**Comment by Tanguygab** [comment]
can players ingame see it or only Discord users?

**Comment by Tanguygab** [comment]
So it appears that after all this time, I was checking the condition for the sender instead of the viewer.... I'll fix it

**Comment by Tanguygab** [comment]
https://github.com/Tanguygab/TAB-Additions/releases/tag/1.6.6

**Comment by Tanguygab** [comment]
do /ver TAB and /ver TAB-Additions

**Comment by Tanguygab** [comment]
can you send me your server's IP?

**Comment by Tanguygab** [comment]
I have reproduced it and correctly fixed it this time 😅  Sorry for the inconvenience
