### ISSUE TITLE
Question about the mention system

### ISSUE THREAD

**Issue by Zarkness** [Tanguygab/TAB-Additions#20]
I saw that your plugin has a mention system and I was wondering if you can create different mentions like for example a mention for the vip rank, a mention for the staff, a mention for everyone that would mention everyone like discord has, besides I was also wondering if you could put a permission to receive that notification and if you could put another permission to put who can use each mention.

**Comment by Tanguygab** [comment]
You can't create different mentions per player, though if you create a condition in TAB and use `%condition:<conditionName>%` then I guess it should work, haven't tried.
There isn't an @everyone mention as of now, cuz it's kinda stupid imo, you just send a message and it's the same thing, it's not like Discord where you can have tons of channels.
 There isn't any permission to send mentions, though if someone ignores you or has mentions disabled with /togglemention, staff can bypass it with `tabadditions.chat.bypass.togglemention` and `tabadditions.chat.bypass.ignore`

**Comment by Zarkness** [comment]
ok thank you very much, and couldn't you add the option to create different mentions?

**Comment by Tanguygab** [comment]
How would that work?

**Comment by Zarkness** [comment]
the function I would give it, would be to create a @staff so that users can mention the staff when necessary.

**Comment by Tanguygab** [comment]
ah, okay, I see what you mean.
Interesting feature, I'll see what I can do

**Comment by Zarkness** [comment]
ok, thank you very much, if you put that you can create any type of mention, I think it would be better because maybe in the future I want to create a mention to mention an event for example and those who have permission to receive the notification, then they will be notified.

**Comment by Tanguygab** [comment]
![image](https://user-images.githubusercontent.com/45695833/229305227-2daff0a1-e146-4a15-af84-6c5105bebe9e.png)

**Comment by Tanguygab** [comment]
https://github.com/Tanguygab/TAB-Additions/releases/tag/1.7.1
