### ISSUE TITLE
Possibility to fix this issue?

### ISSUE THREAD

**Issue by catches** [Tanguygab/TAB-Additions#22]
Normal players can do this:
![image](https://user-images.githubusercontent.com/105005455/204145177-836be088-bc27-4d46-8b19-c2da290f4446.png)

**Comment by Tanguygab** [comment]
try to redownload 1.6.7 https://github.com/Tanguygab/TAB-Additions/releases/download/1.6.7/TAB-Additions-1.6.7.jar

**Comment by Tanguygab** [comment]
It should have registered, weird, I don't think my cmd works in the console though. * and ** are probably also because of Essentials's /msg. Maybe try disabling it in its config.yml 
![image](https://user-images.githubusercontent.com/45695833/204342151-957e9868-7f1e-49c6-9763-27a1a26ca3d9.png)

**Comment by Tanguygab** [comment]
most plugins have a message action like [msg] or [message], I don't really see a reason to be able to use it from console so I didn't add support for it

**Comment by Tanguygab** [comment]
![image](https://user-images.githubusercontent.com/45695833/209854244-30593948-062d-4280-9859-54579e5ed6bc.png)
depending on your configuration, if you have `permission: category`, you'll need `tabadditions.chat.emoji.category.<category>`, if it's `permission: emoji`, you'll need `tabadditions.chat.emoji.<emoji>`, if you don't specify the option, you don't need any permission to use emojis from this category.

**Comment by Tanguygab** [comment]
How would that work?

**Comment by Tanguygab** [comment]
so, it would hide all msgs except private msgs? alright, should I also block the ability to send msgs? like, say "you toggled global chat off!"

**Comment by Tanguygab** [comment]
yeah, just chat messages from other players are blocked, I get it

**Comment by Tanguygab** [comment]
I haven't updated TAB-Additions to newer TAB versions yet, I'll do it. Also, please use a different issue for each issue individually

**Comment by Tanguygab** [comment]
https://github.com/Tanguygab/TAB-Additions/releases/tag/1.6.8
