### ISSUE TITLE
Relational placeholder sorting

### ISSUE THREAD

**Issue by Jqnnies** [Tanguygab/TAB-Additions#23]
I heard that the main TAB plugin stopped plugin requests features, though I don't know if it's a request or a fix but I'll post it here.

TAB has compatibility for relational placeholders and colors, but the problem is that the plugin can't sort them in the tablist (Such as using PLACEHOLDER:%rel_townyadvanced_color%:&a,&b,&9,&c,&e,&f). The only closest thing I can get is sorting by faction/nation, but even then it still doesn't have the same effect.

Either I'm missing something important, or the plugin just can't do it. Which is why I hope this problem can be eventually solved in the future.

**Comment by Tanguygab** [comment]
That's not something I can do easily, and even if I felt like doing this, it would probably be easier to make the changes in the original code rather than on top of it.
