### ISSUE TITLE
Default players can use colors in public chat?

### ISSUE THREAD

**Issue by catches** [Tanguygab/TAB-Additions#25]
I haven't given out any permissions or anything, but it seems like default players can just use color codes in public chat, this doesn't seem to apply to private messaging.

My plugins:
`Plugins (73): ajLeaderboards, AntiPopup, AureliumSkills, BlepFishing, BlueSlimeCore (SirBlobmanAPI, SirBlobmanCore, XSeries), BottledXP, Chunky, Citizens, Coins, CombatLogX, ConditionalTextPlaceholders, CoreProtect, CraftingStore, DeathMessages, DecentHolograms, DeluxeMenus, DeluxeTags, DiscordSRV, eco, EcoEnchants, Essentials, ExcellentCrates, F3Name, Factions, FastAsyncWorldEdit (WorldEdit), floodgate, FrozenJoin, Geyser-Spigot, GSit, HeadDatabase, Infiniteannouncements, InteractiveChat, InteractiveChatDiscordSrvAddon, InvadedLandsEvents, InventoryRollbackPlus, InvUnload, LuckPerms, Maintenance, MobsToEggs, Multiverse-Core, MyCommand, MyPet, MythicMobs, NexEngine, OpenInv, PlaceholderAPI, PlayerAuctions, PlayerWarps, ProtocolLib, RTP, Sellwand, Sentinel, ServerListPlus, ShopGUIPlus, ShopGUIPlusSilkSpawnersBridge, SilkSpawners, spark, SuperVanish, TAB, TAB-Additions, TradeSystem, Tweakin, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidGen, VoidSpawn, VoteParty, Votifier, Vouchers, WorldGuard, YamipaPlugin`

**Comment by Tanguygab** [comment]
can you try on a test server with just TAB, TAB-Additions and PAPI to see if it happens as well?
If it doesn't, try adding back all your other plugins 1 by 1 or 2 by 2 to see which one does it

**Comment by Tanguygab** [comment]
yup, it does, if you don't want that, then you can deny the permission `tabadditions.chat.color.rgb`

**Comment by Tanguygab** [comment]
Welp, can confirm that this did not work lol
Added here (same permission) https://github.com/Tanguygab/TAB-Additions/releases/download/untagged-6386af2526214e55166b/TAB-Additions-1.7.1-SNAPSHOT.jar
