### ISSUE TITLE
Clear chat only clears chat for player executing the command, not the whole server chat

### ISSUE THREAD

**Issue by catches** [Tanguygab/TAB-Additions#26]
POV of 2 different accounts:
![image](https://user-images.githubusercontent.com/105005455/218580208-bd8cefd2-07c9-4dc9-b984-8475fa87d1eb.png)
![image](https://user-images.githubusercontent.com/105005455/218580270-c630969a-f4ab-4898-acbf-a836606ff676.png)

**Comment by Tanguygab** [comment]
OH my bad xD I never realized that

**Comment by Tanguygab** [comment]
Fixed https://github.com/Tanguygab/TAB-Additions/releases/download/1.6.8/TAB-Additions-1.6.8.jar
