### ISSUE TITLE
For chat emojis, possible to be able to give category and emoji at the same time?

### ISSUE THREAD

**Issue by catches** [Tanguygab/TAB-Additions#27]
For example, for chat emojis, you have to choose  between either category or emoji, but can we give both? Like I can either give the entire category, or just one emoji from that category.

**Comment by Tanguygab** [comment]
> For example, for chat emojis, you have to choose between either category or emoji, but can we give both? Like I can either give the entire category, or just one emoji from that category.

I guess I could do that, I'm just no really active on this plugin anymore, mostly fixing a few bugs but otherwise, I'd need to find the motivation to change that, sorry.



> Also btw the /clearchat doesn't really clear the chat, since players can just scroll up a bit. ![image](https://user-images.githubusercontent.com/105005455/220228381-70b56ee4-47a0-4436-976a-4c2427f4e3cb.png) ![image](https://user-images.githubusercontent.com/105005455/220228396-90fb2de9-6881-4427-b17a-25b3d71cc64b.png)

That's why I added an option to increase the amount of lines that are cleared

**Comment by Tanguygab** [comment]
Idk if you're still interested, but I've reorganized the code around emojis and added the ability to use both the category and emoji permission at the same time: the plugin will first check if you have the category permission, if not, it will check if you have the specific emoji permission.
https://github.com/Tanguygab/TAB-Additions/releases/download/untagged-6386af2526214e55166b/TAB-Additions-1.7.1-SNAPSHOT.jar
