### ISSUE TITLE
Chat Feature Not Working

### ISSUE THREAD

**Issue by RebelMythik** [Tanguygab/TAB-Additions#29]
https://mclo.gs/Z5mrUpr

Fresh install with TAB and Tab Additons enabling chat feature causes that error when a chat message is sent.

**Comment by Tanguygab** [comment]
thanks, I'll fix it

**Comment by Tanguygab** [comment]
Should be fixed here https://github.com/Tanguygab/TAB-Additions/releases/download/untagged-2b750c46bfe12cfb2fbc/TAB-Additions-1.7.1-SNAPSHOT.jar

**Comment by RebelMythik** [comment]
Hey! I doesn't seem like I am able to access that link.

**Comment by Tanguygab** [comment]
uh, that might be because I saved the release as a draft, I'll try to change it

**Comment by Tanguygab** [comment]
Here you go: https://github.com/Tanguygab/TAB-Additions/releases/download/1.7.1/TAB-Additions-1.7.1-SNAPSHOT.jar

**Comment by RebelMythik** [comment]
Awesome! Works thanks so much.
