### ISSUE TITLE
some functions are broken

### ISSUE THREAD

**Issue by Slowedgg** [Tanguygab/TAB-Additions#33]
Hi, the emojis function of the plugin does not work as it should, for example in the vips section, the hover does not show correctly.
https://imgur.com/FJrwn2u

default config:
https://imgur.com/odqafVk

**Comment by Tanguygab** [comment]
![TAB-Additions-2.0.3.jar.zip](https://github.com/Tanguygab/TAB-Additions/files/12091298/TAB-Additions-2.0.3.jar.zip)
