### ISSUE TITLE
Use anti-swearing regex to filter out all forms of the n word?

### ISSUE THREAD

**Issue by ghost** [Tanguygab/TAB-Additions#34]
Not sure how I would do this

**Comment by Tanguygab** [comment]
I think this should do the trick `(?i)n[i1l!|¡]gg[ae@3€](r)?`

**Comment by Tanguygab** [comment]
I don't know of any, but there's probably some forums online where people posted all kinds of anti swears regex patterns, you can also test them with a site like regex101 or smth

for your second question, I'll add it

**Comment by Tanguygab** [comment]
o_O

**Comment by Tanguygab** [comment]
fixed, redownload the release

**Comment by Tanguygab** [comment]
;-;

**Comment by Tanguygab** [comment]
set line: " " with a space inside
