### ISSUE TITLE
hover function stopped working in 1.20.4

### ISSUE THREAD

**Issue by Slowedgg** [Tanguygab/TAB-Additions#35]
Hi, I have updated Tab to the latest version and the hover in the chat formats no longer works.

**Comment by Tanguygab** [comment]
I'll need a version number and your chat file

**Comment by Slowedgg** [comment]
TAB version 4.1.2
An all-in-one solution that works
Website: https://github.com/NEZNAMY/TAB
Author: NEZNAMY


TAB-Additions version 2.0.5
More features for the plugin TAB !
Author: Tanguygab

You are running the latest version
Previous version: git-Paper-389 (MC: 1.20.4)


chat.yml
https://bin.bloom.host/nepibogoce.less

**Comment by Tanguygab** [comment]
Whoops
![image](https://github.com/Tanguygab/TAB-Additions/assets/45695833/36e00ef2-01ee-480a-93e8-5abcfd130544)
![image](https://github.com/Tanguygab/TAB-Additions/assets/45695833/126c72b1-2791-443b-911f-8ab585191e4f)
I forgot to release an update, doing that right now

**Comment by Tanguygab** [comment]
Published https://github.com/Tanguygab/TAB-Additions/releases/tag/2.0.6
