### ISSUE TITLE
TAB-Additions v2.0.6 (Is it up to date?)

### ISSUE THREAD

**Issue by Slowedgg** [Tanguygab/TAB-Additions#36]
I just updated the plugin and I get this error when trying to enable it.

TAB version 4.1.2
TAB-Additions version 2.0.6
https://bin.birdflop.com/ogoyagaxih.rb

**Comment by Tanguygab** [comment]
![image](https://github.com/Tanguygab/TAB-Additions/assets/45695833/a0c97026-be29-44dc-8d06-c6710acdfa10)
