### ISSUE TITLE
chat color permission

### ISSUE THREAD

**Issue by Slowedgg** [Tanguygab/TAB-Additions#38]
Hello, I wanted to know if there is any permission to write in the chat with colors and formats &k etc. Users of the default format can use colors in the chat but I'm not looking for that, I want to deny the use of colors to certain groups

**Comment by Tanguygab** [comment]
So... somehow I forgot to add the permission check for colors back when I reworked the plugin last year, and no one has ever reported this XD

Here's a jar with the check added back https://github.com/Tanguygab/TAB-Additions/releases/tag/2.0.8, permissions are `tabadditions.chat.color.&<colorcode>` or `tabadditions.chat.color.rgb` for RGB colors
