### ISSUE TITLE
TAB Private Messaging Doesn't Work

### ISSUE THREAD

**Issue by catches** [Tanguygab/TAB-Additions#41]
When I tried /msg, it doesn't show anything, no errors in console
![image](https://github.com/Tanguygab/TAB-Additions/assets/105005455/1f0d75d6-d57b-4eaa-8a85-c26a37b547d4)

**Comment by Tanguygab** [comment]
send your chat.yml

**Comment by Tanguygab** [comment]
found the issue, though I'll have to rework how I'm handling commands. I'll do that tomorrow, thanks for the report

**Comment by Tanguygab** [comment]
Should be fixed here https://github.com/Tanguygab/TAB-Additions/releases/tag/2.0.10
