### ISSUE TITLE
Toggle chat executes twice?

### ISSUE THREAD

**Issue by ghost** [Tanguygab/TAB-Additions#42]
Whenever, I type toggle chat, it sends two times, it seems. Also the tab-addition placeholders seem to be frozen until I click on it
![image](https://github.com/Tanguygab/TAB-Additions/assets/129551266/6c90d747-4343-4205-974b-779e95d5e622)
![image](https://github.com/Tanguygab/TAB-Additions/assets/129551266/5169971b-66ad-4681-a2bc-d51539121c47)

![image](https://github.com/Tanguygab/TAB-Additions/assets/129551266/0aa76bd2-6435-49a0-90e4-d181cbedffb4)

**Comment by Tanguygab** [comment]
I'll check for /togglechat, though for the placeholders, idk which plugin you're using but you need to use `%tab_placeholder_<placeholder>%` since those are registered as TAB placeholders and not PlaceholderAPI, so `%tab_placeholder_chat-status%` etc...

**Comment by Tanguygab** [comment]
Should be fixed https://github.com/Tanguygab/TAB-Additions/releases/tag/2.0.11
