### ISSUE TITLE
Vanish support?

### ISSUE THREAD

**Issue by ghost** [Tanguygab/TAB-Additions#44]
Hey, I was wondering if it was possible to add vanish support for plugins like SuperVanish so players wouldn't be able to /msg you, it would just return Player not found or something, thanks!

**Comment by Tanguygab** [comment]
I hadn't realized you could msg vanish players 😅 I'll fix that

**Comment by Tanguygab** [comment]
Can you try this jar? https://github.com/Tanguygab/TAB-Additions/releases/download/untagged-86f71205adbe3d624032/TAB-Additions-2.0.13.jar should be fixed
