### ISSUE TITLE
Ver 2.0.13 doesnt work with TAB 5.0.1

### ISSUE THREAD

**Issue by 1ntent1on** [Tanguygab/TAB-Additions#45]
As the title says, 2.0.13 doesnt work with TAB 5.0.1 

This server is running Pufferfish version 1.21.1-19-HEAD@8abd47b (2024-10-13T16:44:51Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

Error log: https://pastebin.com/fLPaUDdq

**Comment by Tanguygab** [comment]
Yeah I still haven't updated the plugin. I'll do that soon

**Comment by Tanguygab** [comment]
Spent the last 2 hours updating the plugin, let me know if you find any issues
https://github.com/Tanguygab/TAB-Additions/releases/tag/2.1.0
