### ISSUE TITLE
Chat formatting not working

### ISSUE THREAD

**Issue by blockcrafter21** [Tanguygab/TAB-Additions#8]
i have this style "{%tab_chatprefix%}{%tab_customchatname%}{»%msg%}"
and the output is 
![image](https://user-images.githubusercontent.com/72599189/147827444-cae9679e-68f4-428d-8ac9-b517620f26f2.png)

**Comment by Tanguygab** [comment]
if you don't use hover and click actions, put them all in 1 component, {{%tab_chatprefix%%tab_customchatname%»%msg%}

**Comment by blockcrafter21** [comment]
thanks
